// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrintGrid.Infrastructure.Shared.Persistence;

#nullable disable

namespace PrintGrid.Infrastructure.Shared.Persistence.Migrations
{
    [DbContext(typeof(PrintGridDbContext))]
    partial class PrintGridDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers", "customer");
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "CreatedAt");

                    b.ToTable("models", "customer");
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("PromisedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("orders", "customer");
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", "customer");
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("PromisedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("quotes", "customer");
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedMaterialGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("EstimatedPrintMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("quote_items", "customer");
                });

            modelBuilder.Entity("PrintGrid.Modules.Scheduling.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualPrintMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedPrintMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("InternalDueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("LabId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PlannedEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PlannedStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("InternalDueDate");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("Status", "MachineId");

                    b.ToTable("jobs", "scheduling");
                });

            modelBuilder.Entity("PrintGrid.Modules.Scheduling.Domain.Entities.Lab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FirstPassYield")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OnTimeDeliveryRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("TransitDaysToHub")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("labs", "scheduling");
                });

            modelBuilder.Entity("PrintGrid.Modules.Scheduling.Domain.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AchievableToleranceMm")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinLayerHeightMm")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SpeedFactor")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<List<string>>("_supportedMaterials")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("supported_materials");

                    b.HasKey("Id");

                    b.HasIndex("LabId", "Status");

                    b.ToTable("machines", "scheduling");
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Order", b =>
                {
                    b.OwnsOne("PrintGrid.SharedKernel.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_currency");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "customer");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("PrintGrid.SharedKernel.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("delivery_country");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_district");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("delivery_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("delivery_street");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_ward");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "customer");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("PrintGrid.Modules.Customer.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PrintGrid.Modules.Customer.Domain.ValueObjects.PrintConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ColorCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("color_code");

                            b1.Property<int>("InfillPercent")
                                .HasColumnType("integer")
                                .HasColumnName("infill_percent");

                            b1.Property<decimal>("LayerHeightMm")
                                .HasPrecision(4, 3)
                                .HasColumnType("numeric(4,3)")
                                .HasColumnName("layer_height_mm");

                            b1.Property<string>("MaterialCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("material_code");

                            b1.Property<decimal>("ToleranceMm")
                                .HasPrecision(5, 3)
                                .HasColumnType("numeric(5,3)")
                                .HasColumnName("tolerance_mm");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items", "customer");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.OwnsOne("PrintGrid.SharedKernel.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_currency");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items", "customer");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Quote", b =>
                {
                    b.OwnsOne("PrintGrid.SharedKernel.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_currency");

                            b1.HasKey("QuoteId");

                            b1.ToTable("quotes", "customer");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId");
                        });

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.QuoteItem", b =>
                {
                    b.HasOne("PrintGrid.Modules.Customer.Domain.Entities.Quote", null)
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PrintGrid.Modules.Customer.Domain.ValueObjects.PrintConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("QuoteItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ColorCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("color_code");

                            b1.Property<int>("InfillPercent")
                                .HasColumnType("integer")
                                .HasColumnName("infill_percent");

                            b1.Property<decimal>("LayerHeightMm")
                                .HasPrecision(4, 3)
                                .HasColumnType("numeric(4,3)")
                                .HasColumnName("layer_height_mm");

                            b1.Property<string>("MaterialCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("material_code");

                            b1.Property<decimal>("ToleranceMm")
                                .HasPrecision(5, 3)
                                .HasColumnType("numeric(5,3)")
                                .HasColumnName("tolerance_mm");

                            b1.HasKey("QuoteItemId");

                            b1.ToTable("quote_items", "customer");

                            b1.WithOwner()
                                .HasForeignKey("QuoteItemId");
                        });

                    b.OwnsOne("PrintGrid.SharedKernel.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("QuoteItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_currency");

                            b1.HasKey("QuoteItemId");

                            b1.ToTable("quote_items", "customer");

                            b1.WithOwner()
                                .HasForeignKey("QuoteItemId");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("PrintGrid.Modules.Scheduling.Domain.Entities.Job", b =>
                {
                    b.OwnsOne("PrintGrid.Modules.Scheduling.Domain.ValueObjects.JobSpecification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ColorCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("color_code");

                            b1.Property<decimal>("LayerHeightMm")
                                .HasPrecision(4, 3)
                                .HasColumnType("numeric(4,3)")
                                .HasColumnName("layer_height_mm");

                            b1.Property<string>("MaterialCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("material_code");

                            b1.Property<decimal>("MaterialGrams")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("material_grams");

                            b1.Property<string>("Technology")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("technology");

                            b1.Property<decimal>("ToleranceMm")
                                .HasPrecision(5, 3)
                                .HasColumnType("numeric(5,3)")
                                .HasColumnName("tolerance_mm");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("JobId");

                            b1.OwnsOne("PrintGrid.Modules.Scheduling.Domain.ValueObjects.BuildVolume", "RequiredVolume", b2 =>
                                {
                                    b2.Property<Guid>("JobSpecificationJobId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("DepthMm")
                                        .HasPrecision(8, 2)
                                        .HasColumnType("numeric(8,2)")
                                        .HasColumnName("required_depth_mm");

                                    b2.Property<decimal>("HeightMm")
                                        .HasPrecision(8, 2)
                                        .HasColumnType("numeric(8,2)")
                                        .HasColumnName("required_height_mm");

                                    b2.Property<decimal>("WidthMm")
                                        .HasPrecision(8, 2)
                                        .HasColumnType("numeric(8,2)")
                                        .HasColumnName("required_width_mm");

                                    b2.HasKey("JobSpecificationJobId");

                                    b2.ToTable("jobs", "scheduling");

                                    b2.WithOwner()
                                        .HasForeignKey("JobSpecificationJobId");
                                });

                            b1.Navigation("RequiredVolume")
                                .IsRequired();
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("PrintGrid.Modules.Scheduling.Domain.Entities.Machine", b =>
                {
                    b.HasOne("PrintGrid.Modules.Scheduling.Domain.Entities.Lab", null)
                        .WithMany("Machines")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PrintGrid.Modules.Scheduling.Domain.ValueObjects.BuildVolume", "BuildVolume", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DepthMm")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("build_depth_mm");

                            b1.Property<decimal>("HeightMm")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("build_height_mm");

                            b1.Property<decimal>("WidthMm")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("build_width_mm");

                            b1.HasKey("MachineId");

                            b1.ToTable("machines", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.Navigation("BuildVolume")
                        .IsRequired();
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PrintGrid.Modules.Customer.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PrintGrid.Modules.Scheduling.Domain.Entities.Lab", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
