<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PrintGrid.Modules.Analytics.Domain\PrintGrid.Modules.Analytics.Domain.csproj" />
    <ProjectReference Include="..\PrintGrid.Modules.Analytics.Application\PrintGrid.Modules.Analytics.Application.csproj" />
    <ProjectReference Include="..\..\..\PrintGrid.Infrastructure.Shared\PrintGrid.Infrastructure.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

</Project>
