<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PrintGrid.SharedKernel\PrintGrid.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\PrintGrid.Modules\Customer\PrintGrid.Modules.Customer.Domain\PrintGrid.Modules.Customer.Domain.csproj" />
    <ProjectReference Include="..\..\src\PrintGrid.Modules\Customer\PrintGrid.Modules.Customer.Application\PrintGrid.Modules.Customer.Application.csproj" />
    <ProjectReference Include="..\..\src\PrintGrid.Modules\Scheduling\PrintGrid.Modules.Scheduling.Domain\PrintGrid.Modules.Scheduling.Domain.csproj" />
    <ProjectReference Include="..\..\src\PrintGrid.Modules\Scheduling\PrintGrid.Modules.Scheduling.Application\PrintGrid.Modules.Scheduling.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

</Project>
